### ISSUE TITLE
 Getting crash on calling method : -[DeepAR shutdown]

### ISSUE THREAD

**Issue by HemenduK** [DeepARSDK/quickstart-ios-objc#3]
[2022-04-26_14-48-16.2786_-0700-ac852ea1eeb6519febdd55127829b586528cb84e.pdf](https://github.com/DeepARSDK/quickstart-ios-objc/files/8589905/2022-04-26_14-48-16.2786_-0700-ac852ea1eeb6519febdd55127829b586528cb84e.pdf)

- I am getting too many crashes on production build while calling method -[DeepAR shutdown]. I have attached my crash report.
- I am calling -[DeepAR shutdown] this function in dealloc method of ViewController. So, Please help me to resolve this issue.

**Comment by andresteves** [comment]
Happens the same to me. It does not happen every single time but does happen quite often.

**Comment by JelenaKB** [comment]
The example has been updated to include the didFinishShutdown method in the ARDelegate, this change should resolve your issue.
